{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyPWGSIvZV3vJVF33GLMcqX2"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["# Шаг 1: Включаем поддержку 32-битных библиотек и устанавливаем wine32\n","!dpkg --add-architecture i386 && apt update\n","!apt install -y wine32\n","\n","# Шаг 2: Загружаем Windows-версию Python Embed (без GUI)\n","!wget https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip  -O python-embed.zip\n","!unzip python-embed.zip -d win_python/\n","\n","# Шаг 3: Подготовка Python к работе с pip\n","!cp win_python/python310._pth win_python/python._pth\n","with open(\"win_python/sitecustomize.py\", \"w\") as f:\n","    f.write(\"import sys\\nsys.path.append('win_python')\\n\")\n","\n","# Шаг 4: Скачиваем get-pip.py и устанавливаем pip\n","!wget https://bootstrap.pypa.io/get-pip.py  -O get-pip.py\n","!wine win_python/python.exe get-pip.py\n","\n","# Шаг 5: Устанавливаем PyInstaller через pip\n","!wine win_python/python.exe -m pip install PyInstaller\n","\n","# Шаг 6: Создаём тестовый скрипт\n","with open(\"test.py\", \"w\") as f:\n","    f.write(\"\"\"\n","print(\"Привет из .exe!\")\n","input(\"Нажми Enter...\")\n","\"\"\")\n","\n","# Шаг 7: Компилируем в .exe\n","!wine win_python/python.exe -m PyInstaller --noconfirm --onefile --distpath ./dist test.py\n","\n","# Шаг 8: Проверяем, создался ли файл\n","!ls dist/\n","\n","# Шаг 9: Скачиваем готовый .exe\n","from google.colab import files\n","files.download(\"dist/test.exe\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"83hah4KW41xJ","executionInfo":{"status":"error","timestamp":1747832591949,"user_tz":-180,"elapsed":50178,"user":{"displayName":"Vladimir","userId":"12041452336257983801"}},"outputId":"fdc61aec-6e6d-48c2-f4ee-e9b553d426d5"},"execution_count":32,"outputs":[{"output_type":"stream","name":"stdout","text":["\u001b[33m\r0% [Working]\u001b[0m\r            \rHit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease\n","Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease\n","Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease\n","Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]\n","Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease\n","Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease\n","Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease\n","Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease\n","Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease\n","Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease\n","Fetched 129 kB in 1s (99.8 kB/s)\n","Reading package lists... Done\n","Building dependency tree... Done\n","Reading state information... Done\n","86 packages can be upgraded. Run 'apt list --upgradable' to see them.\n","\u001b[1;33mW: \u001b[0mSkipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)\u001b[0m\n","Reading package lists... Done\n","Building dependency tree... Done\n","Reading state information... Done\n","wine32:i386 is already the newest version (6.0.3~repack-1).\n","0 upgraded, 0 newly installed, 0 to remove and 86 not upgraded.\n","--2025-05-21 13:02:33--  https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip\n","Resolving www.python.org (www.python.org)... 151.101.0.223, 151.101.64.223, 151.101.128.223, ...\n","Connecting to www.python.org (www.python.org)|151.101.0.223|:443... connected.\n","HTTP request sent, awaiting response... 200 OK\n","Length: 8629277 (8.2M) [application/zip]\n","Saving to: ‘python-embed.zip’\n","\n","python-embed.zip    100%[===================>]   8.23M  --.-KB/s    in 0.06s   \n","\n","2025-05-21 13:02:33 (132 MB/s) - ‘python-embed.zip’ saved [8629277/8629277]\n","\n","Archive:  python-embed.zip\n","replace win_python/python.exe? [y]es, [n]o, [A]ll, [N]one, [r]ename: A\n","  inflating: win_python/python.exe   \n","  inflating: win_python/pythonw.exe  \n","  inflating: win_python/python310.dll  \n","  inflating: win_python/python3.dll  \n","  inflating: win_python/vcruntime140.dll  \n","  inflating: win_python/vcruntime140_1.dll  \n","  inflating: win_python/LICENSE.txt  \n","  inflating: win_python/pyexpat.pyd  \n","  inflating: win_python/select.pyd   \n","  inflating: win_python/unicodedata.pyd  \n","  inflating: win_python/winsound.pyd  \n","  inflating: win_python/_asyncio.pyd  \n","  inflating: win_python/_bz2.pyd     \n","  inflating: win_python/_ctypes.pyd  \n","  inflating: win_python/_decimal.pyd  \n","  inflating: win_python/_elementtree.pyd  \n","  inflating: win_python/_hashlib.pyd  \n","  inflating: win_python/_lzma.pyd    \n","  inflating: win_python/_msi.pyd     \n","  inflating: win_python/_multiprocessing.pyd  \n","  inflating: win_python/_overlapped.pyd  \n","  inflating: win_python/_queue.pyd   \n","  inflating: win_python/_socket.pyd  \n","  inflating: win_python/_sqlite3.pyd  \n","  inflating: win_python/_ssl.pyd     \n","  inflating: win_python/_uuid.pyd    \n","  inflating: win_python/_zoneinfo.pyd  \n","  inflating: win_python/libcrypto-1_1.dll  \n","  inflating: win_python/libffi-7.dll  \n","  inflating: win_python/libssl-1_1.dll  \n","  inflating: win_python/sqlite3.dll  \n","  inflating: win_python/python310.zip  \n","  inflating: win_python/python310._pth  \n","  inflating: win_python/python.cat   \n","--2025-05-21 13:02:47--  https://bootstrap.pypa.io/get-pip.py\n","Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.0.175, 151.101.64.175, 151.101.128.175, ...\n","Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.0.175|:443... connected.\n","HTTP request sent, awaiting response... 200 OK\n","Length: 2279307 (2.2M) [text/x-python]\n","Saving to: ‘get-pip.py’\n","\n","get-pip.py          100%[===================>]   2.17M  --.-KB/s    in 0.05s   \n","\n","2025-05-21 13:02:47 (40.4 MB/s) - ‘get-pip.py’ saved [2279307/2279307]\n","\n","0050:err:explorer:initialize_display_settings Failed to query current display settings for L\"\\\\\\\\.\\\\DISPLAY1\".\n","\u001b[?25lCollecting pip\u001b[?25h\n","\u001b[?25l  Using cached pip-25.1.1-py3-none-any.whl.metadata (3.6 kB)\u001b[?25h\n","\u001b[?25lCollecting setuptools\u001b[?25h\n","\u001b[?25l  Using cached setuptools-80.8.0-py3-none-any.whl.metadata (6.6 kB)\u001b[?25h\n","\u001b[?25lCollecting wheel\u001b[?25h\n","\u001b[?25l  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)\u001b[?25h\n","\u001b[?25lUsing cached pip-25.1.1-py3-none-any.whl (1.8 MB)\u001b[?25h\n","\u001b[?25lUsing cached setuptools-80.8.0-py3-none-any.whl (1.2 MB)\u001b[?25h\n","\u001b[?25lUsing cached wheel-0.45.1-py3-none-any.whl (72 kB)\u001b[?25h\n","\u001b[?25lInstalling collected packages: wheel, setuptools, pip\u001b[?25h\n","   \u001b[30m----------------------------------------\u001b[m \u001b[32m0/3\u001b[m [wheel]\u001b[33m  WARNING: The script whe\n","el.exe is installed in 'Z:\\content\\win_python\\Scripts' which is not on PATH.\u001b[m\u001b[K\n","\u001b[33m  Consider adding this directory to PATH or, if you prefer to suppress this warn\n","ing, use --no-warn-script-location.\u001b[m\u001b[K\n","   \u001b[91m-------------------------- \u001b[30m-------------\u001b[m \u001b[32m2/3\u001b[m [pip]\u001b[33m  WARNING: The scripts pip.\n","exe, pip3.10.exe and pip3.exe are installed in 'Z:\\content\\win_python\\Scripts' w\n","hich is not on PATH.\u001b[m\u001b[K\n","\u001b[33m  Consider adding this directory to PATH or, if you prefer to suppress this warn\n","ing, use --no-warn-script-location.\u001b[m\u001b[K\n","\u001b[K\u001b[K\u001b[2C\u001b[K\u001b[33m\u001b[1C----------------------------------------\u001b[m\u001b[K\u001b[32m\u001b[1C3/3\u001b[m\u001b[K\u001b[1C[pip]\n","\u001b[?25h\u001b[?25l\u001b[K\u001b[?25h\u001b[?25lSuccessfully installed pip-25.1.1 setuptools-80.8.0 wheel-0.45.1\u001b[?25h\n","00a0:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003\n","0050:err:explorer:initialize_display_settings Failed to query current display settings for L\"\\\\\\\\.\\\\DISPLAY1\".\n","\u001b[?25lZ:\\content\\win_python\\python.exe: No module named pip\n","\u001b[?25h0050:err:explorer:initialize_display_settings Failed to query current display settings for L\"\\\\\\\\.\\\\DISPLAY1\".\n","\u001b[?25lZ:\\content\\win_python\\python.exe: No module named PyInstaller\n","\u001b[?25h1\n"]},{"output_type":"error","ename":"FileNotFoundError","evalue":"Cannot find file: dist/test.exe","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-32-055cf6dde3d1>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     34\u001b[0m \u001b[0;31m# Шаг 9: Скачиваем готовый .exe\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     35\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mgoogle\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcolab\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mfiles\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 36\u001b[0;31m \u001b[0mfiles\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdownload\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"dist/test.exe\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.11/dist-packages/google/colab/files.py\u001b[0m in \u001b[0;36mdownload\u001b[0;34m(filename)\u001b[0m\n\u001b[1;32m    231\u001b[0m   \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0m_os\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpath\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexists\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfilename\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    232\u001b[0m     \u001b[0mmsg\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'Cannot find file: {}'\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfilename\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 233\u001b[0;31m     \u001b[0;32mraise\u001b[0m \u001b[0mFileNotFoundError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[0;34m)\u001b[0m  \u001b[0;31m# pylint: disable=undefined-variable\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    234\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    235\u001b[0m   \u001b[0mcomm_manager\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_IPython\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mkernel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcomm_manager\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mFileNotFoundError\u001b[0m: Cannot find file: dist/test.exe"]}]}]}